[project]
name = "ipa-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sofiaoksin", email = "sofia.oksin@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "streamlit>=1.62.0",
]

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"
